### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by amjadnoor** [chryz-hub/opensource-4-everyone#4]
@chryzcodez 
I spend time for your project and found problem and create PR but you closed my #3 PR and assigned your own. Because I spend my time for your project so, credit goes to me. This is not good for open-source project.

**Comment by amjadnoor** [comment]
What you found by closing my PR?

**Comment by chryzcode** [comment]
> What you found by closing my PR?

I would love to explain something to you. I never said I took the glory of the PR and it was not said I was the on who made the PR, it was you!

I automated the assign to my self because this is a growing community and we don't have enough reviewers. I did this to get notified!

and I never closed the PR, if a pull request is merged, it is closed automatically!

Do not get this wrong

**Comment by chryzcode** [comment]
> @chryzcodez
> I spend time for your project and found problem and create PR but you closed my #3 PR and assigned your own. Because I spend my time for your project so, credit goes to me. This is not good for open-source project.

I did not even assign it to my self, I was just a reviewer of the PR and I merged it when I saw the correction was right! You really need to understand more about open-source and GitHub!

**Comment by amjadnoor** [comment]
Sorry @chryzcodez  brother I was in misunderstanding. I apologize for this type of misunderstanding talk with you. I am always with you.
